# HTTPS 배포용 - docker compose -f docker-compose.yml -f docker-compose.https.yml up -d
services:
  crew:
    ports:
      - "443:3000"  # HTTPS 표준 포트
    environment:
      - USE_HTTPS=true
      - SSL_KEY_PATH=/app/certs/server.key
      - SSL_CERT_PATH=/app/certs/server.crt
    volumes:
      - ./data:/app/data
      - ./certs:/app/certs:ro
